# use ubuntu
FROM ubuntu:22.04

# creating the folder structure
RUN mkdir -p /Data/Ninjas/Mukesh \
    && mkdir -p /Data/Ninjas/Aditya \
    && mkdir -p /Data/Ninjas/Suraj \
    && mkdir -p /Data/Ninjas/Deepak \
    && mkdir -p /Data/Ninjas/Rahul 


# create the user
RUN useradd -ms /bin/bash Mukesh && \
    useradd -ms /bin/bash Aditya && \
    useradd -ms /bin/bash Suraj && \
    useradd -ms /bin/bash Deepak && \
    useradd -ms /bin/bash Rahul 

#setting the ownership
# Set ownership and permissions
# Mukesh can write only to his folder (700)
# Others' folders are read-only for him (555)
RUN chown -R Mukesh:Mukesh /Data/Ninjas/Mukesh && chmod 700 /Data/Ninjas/Mukesh && \
    chown -R Aditya:Aditya /Data/Ninjas/Aditya && chmod 555 /Data/Ninjas/Aditya && \
    chown -R Suraj:Suraj /Data/Ninjas/Suraj && chmod 555 /Data/Ninjas/Suraj && \
    chown -R Deepak:Deepak /Data/Ninjas/Deepak && chmod 555 /Data/Ninjas/Deepak && \
    chown -R Rahul:Rahul /Data/Ninjas/Rahul && chmod 555 /Data/Ninjas/Rahul

# switching current user
USER Mukesh
WORKDIR /Data/Ninjas


# setting the bash
CMD ["/bin/bash"]


