FROM nginx:alpine

#copy the script file

COPY start.sh start.sh

# give executing permission
RUN chmod +x /start.sh

#expose to port
EXPOSE 80

# run the script on container start
CMD [ "bin/sh", "start.sh" ]

